import { defineConfig } from '@playwright/test';

export default defineConfig({
  testDir: '../../performance',
  testMatch: ['phase4c0-stage-decomposition.spec.ts'],
  fullyParallel: false,
  workers: 1,
  retries: 0,
  timeout: 60 * 60 * 1000,
  expect: { timeout: 30_000 },
  reporter: [['line']],
  outputDir: '../../../docs/benchmarks/phase4c0_stage_decomposition/test-results',
  use: {
    baseURL: 'http://127.0.0.1:4173',
    browserName: 'chromium',
    headless: false,
    viewport: { width: 1440, height: 900 },
    deviceScaleFactor: 1,
    colorScheme: 'light',
    actionTimeout: 30_000,
    navigationTimeout: 60_000,
    trace: 'off',
    video: 'off',
    screenshot: 'off',
  },
  webServer: {
    cwd: '../../..',
    command: 'node tests/performance/startPhase2Vite.mjs',
    url: 'http://127.0.0.1:4173/benchmarks/phase4c0-stage-decomposition.html?workload=C0-A',
    reuseExistingServer: false,
    timeout: 120_000,
    stdout: 'pipe',
    stderr: 'pipe',
  },
});
